services:
  - type: web
    name: jarvis
    repo: https://github.com/pb7885082-boop/jarvis.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RENDER_APP_NAME
        value: "jarvis"
      - key: RENDER_API
        value: "rnd_BmVrrSJ7FKhmaR7m6HunqHrOVQEG"
      - key: SESSION_ID
        value: "Jarvis_v600_0y69_94u2_v734_y8z0_70zx_50u8_uv5211:32 PM"
      - key: DATABASE_URL
        value: "postgresql://hope_xhxm_user:aZvGt0VwTvXNsW5vgBMbjNinhu2WNBsL@dpg-d9ci7inavr4c73aba97g-a.oregon-postgres.render.com/hope_xhxm"
      - key: HANDLER
        value: "!"
      - key: WORK_TYPE
        value: "private"
      - key: ERROR_MSG
        value: "true"
      - key: BOT_INFO
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/f23f574f13baaf790f250.jpg"
      - key: AUDIO_DATA
        value: "ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://graph.org/file/76a1d2fe74ba5e5643e16.jpg"
      - key: MEDIA_DATA
        value: "ʟɪꜱᴛᴍᴇɴᴜ;ᴊᴀʀᴠɪꜱ-ᴍᴅ;https://graph.org/file/46ad7e1ba38c82aee6c0d.jpg"
      - key: STICKER_PACKNAME
        value: "ᴃ𝗍／𝗐𝗈𝗋𝗅𝗗𐌌ꙮ⍆ꕶ🌟🐊❳"
      - key: SUDO
        value: "917025673121"
      - key: WARN_COUNT
        value: "3"
      - key: ALLWAYS_ONLINE
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: SAVE_STATUS
        value: "false"
      - key: STATUS_VIEW
        value: "false"
      - key: REJECT_CALL
        value: "false"
